= Document Title
Doc Writer <doc@example.com>
:icontype: svg
:doctype: book
:reproducible:
:source-highlighter: highlight.js
:listing-caption: Listing

A simple http://asciidoc.org[AsciiDoc] document.

== Introduction

A paragraph followed by an unordered list{empty}footnote:[AsciiDoc supports unordered, ordered, and description lists.] with square bullets.footnote:[You may choose from square, disc, and circle for the bullet style.]

[square]
* item 1
* item 2

Here's how you say "`Hello, World!`" in Prawn:

.Create a basic PDF document using Prawn
[source,ruby]
----
require 'prawn'

Prawn::Document.generate 'example.pdf' do
  text 'Hello, World!' // <1>
end
----
<1> Add `Hello, World!` as text

.Icons
====
.Size & title
Do you want to drink a small icon:cocktail[sm] or a tall icon:beer[2x,title=pint] ?

.Fixed-width
icon:ruler-vertical[fw] vertical ruler +
icon:ruler-horizontal[fw] horizontal ruler

.Rotate
icon:flag[rotate=90] +
icon:flag[rotate=180] +
icon:flag[rotate=270] +
icon:flag[flip=horizontal] +
icon:flag[flip=vertical]

.Spin and pulse
We are working on it icon:cog[spin], please wait icon:spinner[role=fa-pulse]

.Octicons
You can icon:repo-forked[set=octicons] me on icon:mark-github[set=octicons]... bip bip bop icon:hubot@octicons[]

.FontAwesome solid (default), regular and brand
icon:address-book[] icon:address-book[set=far] icon:chrome@fab[]
====

== Conclusion

That's all, folks!
